<Project Sdk="Microsoft.NET.Sdk">
	<!--This is an xml comment. Comments have no impact on compiling.-->

	<PropertyGroup>
		<!--This is the .NET version the mod will be compiled with. Don't change it.-->
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>Latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<PropertyGroup>
		<TheLongDarkPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark</TheLongDarkPath>
		<MelonLoaderPath>$(TheLongDarkPath)\MelonLoader\net6</MelonLoaderPath>
		<ModsPath>$(TheLongDarkPath)\Mods</ModsPath>
	</PropertyGroup>

	<!--This is the of packages that the mod references.-->
	<ItemGroup>
		<!--This package contains almost everything a person could possibly need to reference while modding.-->
		<PackageReference Include="STBlade.Modding.TLD.Il2CppAssemblies.Windows" Version="2.51.0" />		
	</ItemGroup>

	<ItemGroup>
		<Reference Include="ComplexLogger">
			<HintPath>$(ModsPath)\ComplexLogger.dll</HintPath>
		</Reference>
		<Reference Include="ModSettings">
			<HintPath>$(ModsPath)\ModSettings.dll</HintPath>
		</Reference>
	</ItemGroup>
	
</Project>
